/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hipifif.pfif;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import net.iharder.dnd.FileDrop;

/**
 *
 * @author ra1nb0w
 */
public class MainWindow extends javax.swing.JFrame {
	
	static File openFile;

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jFileChooser1 = new javax.swing.JFileChooser();
                jAbout1 = new javax.swing.JDialog();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jButton1 = new javax.swing.JButton();
                jHelp1 = new javax.swing.JDialog();
                jButton2 = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextPane1 = new javax.swing.JTextPane();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                menuBar = new javax.swing.JMenuBar();
                fileMenu = new javax.swing.JMenu();
                openMenuItem = new javax.swing.JMenuItem();
                saveMenuItem = new javax.swing.JMenuItem();
                saveAsMenuItem = new javax.swing.JMenuItem();
                exitMenuItem = new javax.swing.JMenuItem();
                editMenu = new javax.swing.JMenu();
                cutMenuItem = new javax.swing.JMenuItem();
                copyMenuItem = new javax.swing.JMenuItem();
                pasteMenuItem = new javax.swing.JMenuItem();
                deleteMenuItem = new javax.swing.JMenuItem();
                helpMenu = new javax.swing.JMenu();
                contentsMenuItem = new javax.swing.JMenuItem();
                aboutMenuItem = new javax.swing.JMenuItem();

                jFileChooser1.setDragEnabled(true);

                jAbout1.setAlwaysOnTop(true);

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jTextArea1.setText("BLabla bla\n\nLicense");
                jTextArea1.setFocusable(false);
                jScrollPane1.setViewportView(jTextArea1);

                jButton1.setText("Ok");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                org.jdesktop.layout.GroupLayout jAbout1Layout = new org.jdesktop.layout.GroupLayout(jAbout1.getContentPane());
                jAbout1.getContentPane().setLayout(jAbout1Layout);
                jAbout1Layout.setHorizontalGroup(
                        jAbout1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jAbout1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jAbout1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jAbout1Layout.createSequentialGroup()
                                                .add(0, 0, Short.MAX_VALUE)
                                                .add(jButton1)))
                                .addContainerGap())
                );
                jAbout1Layout.setVerticalGroup(
                        jAbout1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jAbout1Layout.createSequentialGroup()
                                .add(15, 15, 15)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .add(12, 12, 12)
                                .add(jButton1)
                                .addContainerGap())
                );

                jButton2.setText("Ok");

                jTextPane1.setContentType("Help to be done"); // NOI18N
                jTextPane1.setText("Help to be done");
                jScrollPane2.setViewportView(jTextPane1);

                org.jdesktop.layout.GroupLayout jHelp1Layout = new org.jdesktop.layout.GroupLayout(jHelp1.getContentPane());
                jHelp1.getContentPane().setLayout(jHelp1Layout);
                jHelp1Layout.setHorizontalGroup(
                        jHelp1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jHelp1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jHelp1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                                        .add(jHelp1Layout.createSequentialGroup()
                                                .add(0, 0, Short.MAX_VALUE)
                                                .add(jButton2)))
                                .addContainerGap())
                );
                jHelp1Layout.setVerticalGroup(
                        jHelp1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jHelp1Layout.createSequentialGroup()
                                .add(20, 20, 20)
                                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .add(18, 18, 18)
                                .add(jButton2)
                                .addContainerGap())
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMaximumSize(new java.awt.Dimension(200, 200));
                setMinimumSize(new java.awt.Dimension(200, 200));
                setName("2pfif"); // NOI18N
                setPreferredSize(new java.awt.Dimension(200, 200));
                setResizable(false);

                jLabel1.setText("Drag the file");

                org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .add(54, 54, 54)
                                .add(jLabel1)
                                .addContainerGap(58, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .add(76, 76, 76)
                                .add(jLabel1)
                                .addContainerGap(88, Short.MAX_VALUE))
                );

                fileMenu.setMnemonic('f');
                fileMenu.setText("File");

                openMenuItem.setMnemonic('o');
                openMenuItem.setText("Open");
                openMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                openMenuItemMousePressed(evt);
                        }
                });
                fileMenu.add(openMenuItem);

                saveMenuItem.setMnemonic('s');
                saveMenuItem.setText("Save");
                saveMenuItem.setEnabled(false);
                fileMenu.add(saveMenuItem);

                saveAsMenuItem.setMnemonic('a');
                saveAsMenuItem.setText("Save As ...");
                saveAsMenuItem.setDisplayedMnemonicIndex(5);
                saveAsMenuItem.setEnabled(false);
                fileMenu.add(saveAsMenuItem);

                exitMenuItem.setMnemonic('x');
                exitMenuItem.setText("Exit");
                exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(exitMenuItem);

                menuBar.add(fileMenu);

                editMenu.setMnemonic('e');
                editMenu.setText("Edit");
                editMenu.setEnabled(false);

                cutMenuItem.setMnemonic('t');
                cutMenuItem.setText("Cut");
                editMenu.add(cutMenuItem);

                copyMenuItem.setMnemonic('y');
                copyMenuItem.setText("Copy");
                editMenu.add(copyMenuItem);

                pasteMenuItem.setMnemonic('p');
                pasteMenuItem.setText("Paste");
                editMenu.add(pasteMenuItem);

                deleteMenuItem.setMnemonic('d');
                deleteMenuItem.setText("Delete");
                editMenu.add(deleteMenuItem);

                menuBar.add(editMenu);

                helpMenu.setMnemonic('h');
                helpMenu.setText("Help");

                contentsMenuItem.setMnemonic('c');
                contentsMenuItem.setText("Help");
                contentsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                contentsMenuItemMousePressed(evt);
                        }
                });
                helpMenu.add(contentsMenuItem);

                aboutMenuItem.setMnemonic('a');
                aboutMenuItem.setText("About");
                aboutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                aboutMenuItemMousePressed(evt);
                        }
                });
                helpMenu.add(aboutMenuItem);

                menuBar.add(helpMenu);

                setJMenuBar(menuBar);

                org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
	    System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

        private void aboutMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuItemMousePressed
		// check why not show :)
		jAbout1.setVisible(true);
        }//GEN-LAST:event_aboutMenuItemMousePressed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		jAbout1.dispose();
        }//GEN-LAST:event_jButton1ActionPerformed

        private void openMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuItemMousePressed
		int ret = jFileChooser1.showOpenDialog(this);
		if ( ret == javax.swing.JFileChooser.APPROVE_OPTION) {
			openFile = jFileChooser1.getSelectedFile();
			//JOptionPane.showMessageDialog(this, openFile.toString());
			//CSVReader a = new CSVReader();
			//a.Send(openFile.toString());
			try {
				CSVReader.Send(openFile.toString());
			} catch (IOException e) {
				System.err.print(e);
			}
		}
        }//GEN-LAST:event_openMenuItemMousePressed

        private void contentsMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentsMenuItemMousePressed
                jHelp1.setVisible(true);
        }//GEN-LAST:event_contentsMenuItemMousePressed
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
				//DragDrop();
			}
		});
	}
	
	/*
	 * Drag and Drop method
	 * http://www.iharder.net/current/java/filedrop/
	 */
	/*
	private static void DragDrop() {
		FileDrop funct = new  FileDrop(jPanel1, new FileDrop.Listener()	{ 
			public void  filesDropped( File[] files ) {
			// only first value
			// user while ( File file : files ) {} otherwise
			openFile = files[0];
		}
}); 
	}

*/
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenuItem aboutMenuItem;
        private javax.swing.JMenuItem contentsMenuItem;
        private javax.swing.JMenuItem copyMenuItem;
        private javax.swing.JMenuItem cutMenuItem;
        private javax.swing.JMenuItem deleteMenuItem;
        private javax.swing.JMenu editMenu;
        private javax.swing.JMenuItem exitMenuItem;
        private javax.swing.JMenu fileMenu;
        private javax.swing.JMenu helpMenu;
        private javax.swing.JDialog jAbout1;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JFileChooser jFileChooser1;
        private javax.swing.JDialog jHelp1;
        private javax.swing.JLabel jLabel1;
        private static javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextPane jTextPane1;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JMenuItem openMenuItem;
        private javax.swing.JMenuItem pasteMenuItem;
        private javax.swing.JMenuItem saveAsMenuItem;
        private javax.swing.JMenuItem saveMenuItem;
        // End of variables declaration//GEN-END:variables
}
